
DOC_LABELS = [
    "Authorization Letter",
    "Bill",
    "Cancel/No Show",
    "Clinical Report",
    "Corrected Claim",
    "Denial Letter",
    "Discharge Note",
    "FCE Report",
    "Hospital Authorization",
    "Impairment Rating",
    "Incomplete Discharge Note",
    "Incomplete Initial Evaluation",
    "Incomplete New Order",
    "Incomplete Order",
    "Incomplete Progress Note",
    "Incomplete Radiology Report",
    "Incomplete Visit Notes",
    "Incomplete Evaluation",
    "Injured Worker Demos",
    "Job Description",
    "Medical Notes",
    "Miscellaneous Note",
    "New Order",
    "Open Unit Approval",
    "Order",
    "Progress Notes",
    "Progress Summary Report",
    "Radiology Report",
    "SCA",
    "Shipping Label",
    "Visit Notes"
]
